name: 'bw_project'
version: '1.0'
config-version: 2

profile: 'bw_project'

models:
  bw_project:
    staging:
      +schema: staging
      +materialized: view
    reporting:
      +schema: reporting
      +materialized: view